/* SQL DATA ANALYSIS QUERIES Using EDA (Exploratory Data Analysis) */

--Explore All Objects In the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore All Columns In the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
Where TABLE_NAME = 'dim_customers'

--Dimensions Exploration

Select Distinct country from gold.dim_customers

Select Distinct category,subcategory , product_name from gold.dim_products
order by 1,2,3

-- Date Exploration
select 
min(order_date) as first_order_date,  
max(order_date) as last_order_date,
DATEDIFF(year,min(order_date),max(order_date)) AS order_range_year,
DATEDIFF(month,min(order_date),max(order_date)) AS order_range_month
from gold.fact_sales

--Find the youngest and the oldest customer
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;

--Measure Exploration
--Find the Total Sales
SELECT SUM(sales_amount) As total_sales from gold.fact_sales
--Find how many items are sold
SELECT SUM(quantity) As total_quantity from gold.fact_sales
--Find the average selling price
SELECT AVG(price) As avg_price from gold.fact_sales
--Find the Total number of Orders
SELECT COUNT(order_number) As total_orders from gold.fact_sales
SELECT COUNT(DISTINCT order_number) As total_orders from gold.fact_sales
--Find the total number of products
SELECT COUNT(product_key) As total_product from gold.dim_products
--Find the total number of customers
SELECT COUNT(customer_key) As total_customers from gold.dim_customers
--Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) As total_customers from gold.fact_sales

--Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr.Orders', COUNT (DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT (product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers

--Magnitude

--Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average costs in each category?
SELECT
category,
avg(cost) AS average_costs_each_category
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs_each_category DESC

--What is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find total revenue is generated by each customer

SELECT 
c.customer_key,
c.full_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.full_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?

SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC

---Ranking

--Which 5 products generate the highest revenue?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--What are the 5 worst-performing products in terms of sales?


SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

--
SELECT *
FROM(
    SELECT
    p.product_name,
    SUM(f.sales_amount) total_revenue,
    ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
    GROUP BY p.product_name)t
WHERE rank_products <=5

--Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_key,
c.full_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.full_name
ORDER BY total_revenue DESC

--The 3 customers with the fewest orders placed
SELECT TOP 3
c.customer_key,
c.full_name,
COUNT (DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.full_name
ORDER BY total_orders
